CREATE DATABASE IF NOT EXISTS WORLD_LAYOFFS;
USE WORLD_LAYOFFS;
SELECT * FROM LAYOFFS;

-- 1. REMOVE DUPLICATES
-- 2. STANDARDIZE THE DATA(EG. CORRECTING THE SPELLINGS)
-- 3. NULL VALUES OR BLANK VALUES
-- 4. REMOVE ANY UNNECESSARY COLUMNS
-- DELETING ANY COLUMNS IN THE RAW DATA WILL CREATE PROBLEMS IN REAL TIME, 
-- SO WE HAVE TO MAKE STAGING i.e, CREATING ONE COPY OF RAW DATA AND WE CAN DO ANY THING THERE

CREATE TABLE LAYOFFS_STAGING LIKE LAYOFFS;
INSERT INTO LAYOFFS_STAGING SELECT * FROM LAYOFFS; 
SELECT *, ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS)
 AS ROW_NUM FROM LAYOFFS_STAGING;

WITH DUPLICATES AS (SELECT *, ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS)
 AS ROW_NUM FROM LAYOFFS_STAGING)
SELECT * FROM DUPLICATES WHERE ROW_NUM>1;

CREATE TABLE `layoffs_staging2` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
  `ROW_NUM` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM LAYOFFS_STAGING2 WHERE ROW_NUM>1;
INSERT INTO LAYOFFS_STAGING2 SELECT *, ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS)
 AS ROW_NUM FROM LAYOFFS_STAGING;
DELETE FROM LAYOFFS_STAGING2 WHERE ROW_NUM>1;
SET SQL_SAFE_UPDATES=0;

-- STANDARDIZING DATA

SELECT COMPANY, TRIM(COMPANY) FROM LAYOFFS_STAGING2;
UPDATE LAYOFFS_STAGING2 SET COMPANY=TRIM(COMPANY);

SELECT DISTINCT INDUSTRY FROM LAYOFFS_STAGING2 ORDER BY 1;
SELECT * FROM LAYOFFS_STAGING2 WHERE INDUSTRY LIKE 'CRYPT%';
UPDATE LAYOFFS_STAGING2 SET INDUSTRY='CRYPTO' WHERE INDUSTRY='CRYPTOCURRENCY';

SELECT DISTINCT COUNTRY FROM LAYOFFS_STAGING2 ORDER BY 1;
SELECT DISTINCT COUNTRY,TRIM(TRAILING '.' FROM COUNTRY) FROM LAYOFFS_STAGING2 ORDER BY 1;
UPDATE LAYOFFS_STAGING2 SET COUNTRY=TRIM(TRAILING '.' FROM COUNTRY) WHERE COUNTRY LIKE 'UNITED STATES%';

SELECT `DATE`, STR_TO_DATE(`DATE`,'%m/%d/%Y') FROM LAYOFFS_STAGING2;
UPDATE LAYOFFS_STAGING2 SET `DATE`=STR_TO_DATE(`DATE`,'%m/%d/%Y');
ALTER TABLE LAYOFFS_STAGING2 MODIFY COLUMN `DATE` DATE;

-- NULL AND BLANKS

SELECT * FROM LAYOFFS_STAGING2 WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;
SELECT * FROM LAYOFFS_STAGING2 WHERE INDUSTRY IS NULL OR INDUSTRY='';
SELECT * FROM LAYOFFS_STAGING2 WHERE COMPANY='AIRBNB';
 
SELECT T1.INDUSTRY,T2.INDUSTRY FROM LAYOFFS_STAGING2 AS T1
JOIN LAYOFFS_STAGING2 AS T2 ON T1.COMPANY=T2.COMPANY AND T1.LOCATION=T2.LOCATION
WHERE (T1.INDUSTRY IS NULL OR T1.INDUSTRY='') AND T2.INDUSTRY IS NOT NULL;

UPDATE LAYOFFS_STAGING2 SET INDUSTRY=NULL WHERE INDUSTRY='';

UPDATE LAYOFFS_STAGING2 AS T1 JOIN LAYOFFS_STAGING2 AS T2 ON T1.COMPANY=T2.COMPANY 
SET T1.INDUSTRY=T2.INDUSTRY
WHERE T1.INDUSTRY IS NULL AND T2.INDUSTRY IS NOT NULL;

DELETE FROM LAYOFFS_STAGING2 WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;

ALTER TABLE LAYOFFS_STAGING2 DROP COLUMN ROW_NUM;

SELECT * FROM LAYOFFS_STAGING2;
