-- EXPLORATORY DATA ANALYSIS
SELECT * FROM LAYOFFS_STAGING2;

SELECT * FROM LAYOFFS_STAGING2 WHERE TOTAL_LAID_OFF=(SELECT MAX(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2);

SELECT * FROM LAYOFFS_STAGING2 WHERE PERCENTAGE_LAID_OFF=1;

SELECT COMPANY,SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2 GROUP BY COMPANY ORDER BY 2 DESC;

SELECT MIN(`DATE`),MAX(`DATE`) FROM LAYOFFS_STAGING2;

SELECT INDUSTRY,SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2 GROUP BY INDUSTRY ORDER BY 2 DESC;

SELECT COUNTRY,SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2 GROUP BY COUNTRY ORDER BY 2 DESC;

SELECT YEAR(`DATE`),SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2 GROUP BY YEAR(`DATE`) ORDER BY 2 DESC;

-- ROLLING SUM OF TOTAL_LAID_OFF BY MONTH 
SELECT  MONTHNAME(`DATE`) AS `MONTH`,SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2 GROUP BY `MONTH`;

SELECT SUBSTRING(`DATE`,1,7) AS `MONTH`,
SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2 
WHERE SUBSTRING(`DATE`,1,7) IS NOT NULL 
GROUP BY `MONTH` ORDER BY 1 ASC;

WITH ROLLING_TOTAL AS (SELECT SUBSTRING(`DATE`,1,7) AS `MONTH`,
SUM(TOTAL_LAID_OFF) AS R_T FROM LAYOFFS_STAGING2 
WHERE SUBSTRING(`DATE`,1,7) IS NOT NULL 
GROUP BY `MONTH` ORDER BY 1 ASC) 
SELECT `MONTH`,R_T,SUM(R_T) OVER(ORDER BY `MONTH`) AS RT FROM ROLLING_TOTAL;

SELECT COMPANY, YEAR(`DATE`) AS `YEAR`,SUM(TOTAL_LAID_OFF) AS TOTAL_LAID_OFFS
FROM LAYOFFS_STAGING2 
GROUP BY COMPANY, YEAR(`DATE`) 
ORDER BY 1;

WITH COMPANY_YEAR AS (SELECT COMPANY, YEAR(`DATE`) AS `YEAR`,SUM(TOTAL_LAID_OFF) AS TOTAL_LAID_OFFS
FROM LAYOFFS_STAGING2 
GROUP BY COMPANY, YEAR(`DATE`) ), 
COMPANY_RANKING AS (
SELECT *, DENSE_RANK() OVER(PARTITION BY `YEAR` ORDER BY TOTAL_LAID_OFFS DESC) AS RANKING 
FROM COMPANY_YEAR WHERE `YEAR` IS NOT NULL)
SELECT * FROM COMPANY_RANKING WHERE RANKING<=5;










